"""Publish the tested REST stack samples: embed them for the hub and package a ZIP."""
import json
from pathlib import Path
from zipfile import ZipFile, ZIP_DEFLATED

root = Path(__file__).resolve().parents[1]
source = root / "examples/rest-stacks"
files = ["README.md", "express/server.cjs", "nextjs/lib/tasks.ts", "nextjs/app/api/tasks/route.ts",
         "nextjs/app/api/tasks/[id]/route.ts", "fastapi/main.py", "spring/TaskController.java",
         "clients/TaskList.jsx", "clients/styles.css", "clients/client.py", "clients/client.ps1", "clients/curl.sh"]

code = {name: (source / name).read_text(encoding="utf-8") for name in files if name != "README.md"}
script = ("// Generated by scripts/build-stacks.py from examples/rest-stacks. Do not edit by hand.\n"
          "(function (root) {\n  'use strict';\n  const code = " + json.dumps(code, indent=2, ensure_ascii=False) + ";\n"
          "  if (typeof module === 'object' && module.exports) module.exports = code; else root.InterviewStackCode = code;\n"
          "})(typeof window === 'object' ? window : globalThis);\n")
(root / "dist/stacks-code.js").write_text(script, encoding="utf-8")

with ZipFile(root / "dist/downloads/rest-stacks.zip", "w", ZIP_DEFLATED) as archive:
    for name in files:
        archive.write(source / name, name)
print(f"Embedded {len(code)} samples and packaged {len(files)} files: rest-stacks.zip")
